Add-bookings, test passed
V-Levchenkov/Shareit pull request #3
Opened 2022-09-06 12:09 UTC by V-Levchenkov

2022-09-07 06:29 UTC, kukolev requested changes

2022-09-07 06:29 UTC, kukolev commented on pom.xml
> +		<version>2.7.2</version>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-07 06:29 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> searchBookingByBooker_IdAndItem_IdAndEndIsBefore(long id, long itemId, LocalDateTime time);
Нарушение кодстайла: название методов должно быть выполнено в стиле camelCase.

Аналогично нужно поправить и остальные методы.

2022-09-07 06:29 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> searchBookingByItem_Owner_IdAndStartIsAfterOrderByStartDesc(long id, LocalDateTime time);
По моему такие методы очень плохо читаются в коде. Будет лучше, если названия будут короткими, а логика поиска будет реализована в `@Query`

2022-09-07 06:29 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +@Slf4j
Нужно добавить логи в коде или убрать аннотацию. Без логов аннотация лишняя.

2022-09-07 06:29 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +                //null,
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-07 06:29 UTC, kukolev commented on src/main/resources/schema.sql
> +--CREATE TABLE IF NOT EXISTS requests (
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-07 06:29 UTC, kukolev commented on src/main/resources/schema.sql
> +    --request_id BIGINT,
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-07 06:29 UTC, kukolev commented on src/main/resources/schema.sql
> +    --CONSTRAINT fk_items_to_request FOREIGN KEY(request_id) REFERENCES requests(request_id)
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-07 06:36 UTC, V-Levchenkov commented on pom.xml
> +		<version>2.7.2</version>
Done

2022-09-07 06:44 UTC, V-Levchenkov commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> searchBookingByBooker_IdAndItem_IdAndEndIsBefore(long id, long itemId, LocalDateTime time);
Done

2022-09-07 06:44 UTC, V-Levchenkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +@Slf4j
Done

2022-09-07 08:04 UTC, V-Levchenkov commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +                //null,
Done

2022-09-07 08:04 UTC, V-Levchenkov commented on src/main/resources/schema.sql
> +--CREATE TABLE IF NOT EXISTS requests (
Done

2022-09-07 08:04 UTC, V-Levchenkov commented on src/main/resources/schema.sql
> +    --request_id BIGINT,
Done

2022-09-07 08:05 UTC, V-Levchenkov commented on src/main/resources/schema.sql
> +    --CONSTRAINT fk_items_to_request FOREIGN KEY(request_id) REFERENCES requests(request_id)
Done

2022-09-07 08:11 UTC, V-Levchenkov commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> searchBookingByItem_Owner_IdAndStartIsAfterOrderByStartDesc(long id, LocalDateTime time);
Данные методы сделаны с целью показать, что теоретический материал по использованию упрощенных запросов к базе данных усвоен. Методы написаны по примерам из теоретической части спринта.

2022-09-07 16:47 UTC, kukolev requested changes

2022-09-07 16:47 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +    List<Comment> findAllByItem_Id(long id);
Нарушение кодстайла: название методов должно быть выполнено в стиле camelCase.

2022-09-07 16:47 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    //POST /items/{itemId}/comment
По моему этот комментарий лишний. По аннотации и так понятно за что отвечает метод. Если комментарий все таки нужен, то нужно так-же добавить аналогичные комментарии во все методы всех контроллеров для единообразия.

2022-09-07 17:40 UTC, V-Levchenkov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    //POST /items/{itemId}/comment
Недосмотрел когда чистил лишние комментарии.
Done

2022-09-07 21:03 UTC, kukolev requested changes

2022-09-07 21:03 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @JoinColumn(name = "itemId")
Тут нужно исправить на item_id, как было, т.к. название колонки в БД все таки item_id.

2022-09-08 05:44 UTC, V-Levchenkov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @JoinColumn(name = "itemId")
Done

2022-09-08 20:44 UTC, kukolev approved these changes

2022-09-09 03:39 UTC, merged