Add item requests Sprint 15
V-Levchenkov/Shareit pull request #4
Opened 2022-09-19 05:42 UTC by V-Levchenkov

2022-09-19 17:16 UTC, kukolev requested changes

2022-09-19 17:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    public BookingDtoSimple toBookingDtoSimple(Booking booking) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-09-19 17:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> searchBookingByBookerIdAndItemIdAndEndIsBeforeAndStatus(long id, long itemId,
По моему такие методы очень плохо читаются в коде. Будет лучше, если названия будут короткими, а логика поиска будет реализована в `@Query`

2022-09-19 17:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +@Slf4j
Логику сервисов лучше покрыть логами. Так будет проще анализировать поведение программы, если что-то пойдет не так.

2022-09-19 17:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +@Slf4j
Логику сервисов лучше покрыть логами. Так будет проще анализировать поведение программы, если что-то пойдет не так.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    ItemRepository itemRepository;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    void searchBookingByItem_Owner_IdAndStartIsAfter() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    void findByBooker_IdAndStartAfter() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    void findBookingsByItem_IdAndStartIsAfterOrderByStartDesc() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    void findCurrentBookingsByBooker_Id() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    void findCurrentBookingsByItem_Owner_Id() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    void findAll() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    void save() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +class BookingServiceImplTest {
Названия тестов в классе не отображают предназначение теста. Названия тестов можно делать многословными, чтобы из названия было понятно что и как проверяет тест.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    void findAllByItemOwnerId() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +class ItemControllerTest {
Названия тестов в классе не отображают предназначение теста. Названия тестов можно делать многословными, чтобы из названия было понятно что и как проверяет тест.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/repository/CommentRepositoryTest.java
> +class CommentRepositoryTest {
Названия тестов в классе не отображают предназначение теста. Названия тестов можно делать многословными, чтобы из названия было понятно что и как проверяет тест.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/repository/CommentRepositoryTest.java
> +    ItemRepository itemRepository;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/repository/ItemRepositoryTest.java
> +    ItemRepository itemRepository;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceImplTest.java
> +class ItemServiceImplTest {
Названия тестов в классе не отображают предназначение теста. Названия тестов можно делать многословными, чтобы из названия было понятно что и как проверяет тест.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceImplTest.java
> +    void saveComment() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/controller/ItemRequestControllerTest.java
> +class ItemRequestControllerTest {
Названия тестов в классе не отображают предназначение теста. Названия тестов можно делать многословными, чтобы из названия было понятно что и как проверяет тест.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/repository/ItemRequestRepositoryTest.java
> +    ItemRepository itemRepository;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/repository/ItemRequestRepositoryTest.java
> +class ItemRequestRepositoryTest {
Названия тестов в классе не отображают предназначение теста. Названия тестов можно делать многословными, чтобы из названия было понятно что и как проверяет тест.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/service/ItemRequestServiceImplTest.java
> +class ItemRequestServiceImplTest {
Названия тестов в классе не отображают предназначение теста. Названия тестов можно делать многословными, чтобы из названия было понятно что и как проверяет тест.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/controller/UserControllerTest.java
> +    UserService userService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/service/UserServiceImplTest.java
> +    UserService userService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/service/UserServiceImplTest.java
> +class UserServiceImplTest {
Названия тестов в классе не отображают предназначение теста. Названия тестов можно делать многословными, чтобы из названия было понятно что и как проверяет тест.

2022-09-19 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/controller/UserControllerTest.java
> +class UserControllerTest {
Названия тестов в классе не отображают предназначение теста. Названия тестов можно делать многословными, чтобы из названия было понятно что и как проверяет тест.

2022-09-20 05:24 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    ItemRepository itemRepository;
done

2022-09-20 05:24 UTC, V-Levchenkov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    public BookingDtoSimple toBookingDtoSimple(Booking booking) {
Не согласен, т.к. это Dto и не несет никакой угрозе безопасности, и дабы не плодить объекты в коде считаю, что лучше оставить так.

2022-09-20 05:24 UTC, V-Levchenkov commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> searchBookingByBookerIdAndItemIdAndEndIsBeforeAndStatus(long id, long itemId,
В моем видении так будет более информативно, т.к. понятно чего хочет этот метод, так же как и в прошлом спринте мы уже решили, что такая реализация будет соответствовать представленной теоретической части.

2022-09-20 05:26 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/user/service/UserServiceImplTest.java
> +    UserService userService;
done

2022-09-20 05:27 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/user/controller/UserControllerTest.java
> +    UserService userService;
done

2022-09-20 05:27 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/requests/repository/ItemRequestRepositoryTest.java
> +    ItemRepository itemRepository;
done

2022-09-20 05:28 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/item/repository/ItemRepositoryTest.java
> +    ItemRepository itemRepository;
done

2022-09-20 05:29 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/item/repository/CommentRepositoryTest.java
> +    ItemRepository itemRepository;
done

2022-09-20 05:55 UTC, V-Levchenkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +@Slf4j
done

2022-09-20 06:26 UTC, V-Levchenkov commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +@Slf4j
done

2022-09-20 06:50 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    void searchBookingByItem_Owner_IdAndStartIsAfter() {
done

2022-09-20 06:56 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    void searchBookingByItem_Owner_IdAndStartIsAfter() {
done

2022-09-20 07:03 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    void findBookingsByItem_IdAndStartIsAfterOrderByStartDesc() {
done

2022-09-20 07:05 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    void findCurrentBookingsByBooker_Id() {
refactor, done

2022-09-20 07:05 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    void findCurrentBookingsByItem_Owner_Id() {
refactor, done

2022-09-20 07:16 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    void findAll() {
refactor, done

2022-09-20 07:18 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    void save() {
Прошу пересмотреть замечание, т.к. не вижу здесь двусмысленности в тесте, он проверяет сохранение и только.

2022-09-20 07:23 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +class BookingServiceImplTest {
done

2022-09-20 07:47 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    void findAllByItemOwnerId() {
refactor, done

2022-09-20 07:48 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +class ItemControllerTest {
done

2022-09-20 07:53 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/item/repository/CommentRepositoryTest.java
> +class CommentRepositoryTest {
done

2022-09-20 08:15 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    void findByBooker_IdAndStartAfter() {
done

2022-09-20 08:17 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceImplTest.java
> +class ItemServiceImplTest {
done

2022-09-20 08:22 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceImplTest.java
> +    void saveComment() {
done

2022-09-20 08:23 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/requests/repository/ItemRequestRepositoryTest.java
> +class ItemRequestRepositoryTest {
Done

2022-09-20 08:24 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/requests/service/ItemRequestServiceImplTest.java
> +class ItemRequestServiceImplTest {
done

2022-09-20 08:26 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/user/service/UserServiceImplTest.java
> +class UserServiceImplTest {
done

2022-09-20 08:26 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/user/controller/UserControllerTest.java
> +class UserControllerTest {
done

2022-09-20 08:36 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/requests/controller/ItemRequestControllerTest.java
> +class ItemRequestControllerTest {
done

2022-09-20 17:09 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    public BookingDtoSimple toBookingDtoSimple(Booking booking) {
В предыдущем замечании я неверно идентифицировал проблему. Проблема серьезней. Судя по всему этот код нужен только для вспомогательных целей в тестах.

Важно, чтобы тестовый код не перемешивался с основным. Иначе есть риск, что тестовый код попадет в продакшен.  Этот маппинг и сам класс BookingDtoSimple нужно перенести в тесты. В тестах можно сделать отдельную тестовую утилиту в которой будет этот маппинг, это распространенная практика.

2022-09-20 17:09 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    public BookingDtoSimple toBookingDtoSimple(Booking booking) {
На самом деле дела не в приватности. Написал в новом замечании. Если хотите, то давай обсудим в слаке.

2022-09-20 17:11 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> searchBookingByBookerIdAndItemIdAndEndIsBeforeAndStatus(long id, long itemId,
Еще раз повторю, что в продакшене так никто не делает. Это плохая практика и делать так я не советую, т.к. вы привыкаете к плохой практике. Окей, дело ваше, т.к. строгих стандартов на длину названий методов в проекте нет, но мои рекомендации в силе.

2022-09-20 17:13 UTC, kukolev requested changes

2022-09-20 17:13 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        log.info("Поиск по bookingId");
При логировании лучше добавлять информацию о текущих значениях параметров, чтобы при анализе было понятно о чем идет речь. Здесь будет полезно добавить значение переменной «bookingId».

Аналогично рекомендую поправить в остальных частях кода.

2022-09-21 04:38 UTC, V-Levchenkov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    public BookingDtoSimple toBookingDtoSimple(Booking booking) {
done

2022-09-21 04:52 UTC, V-Levchenkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        log.info("Поиск по bookingId");
done + userSevice logs

2022-09-21 16:13 UTC, kukolev requested changes

2022-09-21 16:13 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        log.info("Поиск по bookingId: " + bookingId);
При логировании лучше использовать возможности библиотеки и пользоваться плейсхолдерами `{}` вместо конкатенации строк. Лучше так: `log.warn("Some warning text for {}", val)` вместо `log.warn("Some warning text for " + val)` или `log.warn(String.format("Some warning text for %s", val))` . Так код смотрится проще и тратится меньше ресурсов.

Аналогично нужно поправить в остальных местах кода, где есть логирование.

2022-09-21 16:13 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/bookingTestUtils/TestUtils.java
> +    public BookingDtoSimple toBookingDtoSimple(Booking booking) {
Лучше сделать метод статическим, т.к. в экземпляре класса нет смысла и тогда не нужно будет создавать экземпляры класса в тестах.

2022-09-21 16:37 UTC, V-Levchenkov commented on src/test/java/ru/practicum/shareit/booking/bookingTestUtils/TestUtils.java
> +    public BookingDtoSimple toBookingDtoSimple(Booking booking) {
done

2022-09-21 16:51 UTC, V-Levchenkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        log.info("Поиск по bookingId: " + bookingId);
done

2022-09-22 06:41 UTC, kukolev approved these changes

2022-09-22 06:44 UTC, merged