Add docker Sprint 16
V-Levchenkov/Shareit pull request #7
Opened 2022-09-29 07:30 UTC by V-Levchenkov

2022-09-30 10:57 UTC, kukolev requested changes

2022-09-30 10:57 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +											  @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-30 10:57 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.error("Unknown state: UNSUPPORTED_STATUS" + "\n" + e.getMessage());
При логировании лучше использовать возможности библиотеки и пользоваться плейсхолдерами `{}` вместо конкатенации строк. Лучше так: `log.warn("Some warning text for {}", val)` вместо `log.warn("Some warning text for " + val)` или `log.warn(String.format("Some warning text for %s", val))` . Так код смотрится проще и тратится меньше ресурсов.

Аналогично нужно поправить в остальных местах кода, где есть логирование.

2022-09-30 10:57 UTC, kukolev commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-30 10:57 UTC, kukolev commented on server/pom.xml
> +	<modelVersion>4.0.0</modelVersion>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-30 10:57 UTC, kukolev commented on server/src/test/java/ru/practicum/shareit/item/repository/CommentRepositoryTest.java
> +    ItemRepository itemRepository;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

Не понятно зачем здесь корректный код был исправлен. Нужно вернуть private здесь и в остальных тестах.

2022-09-30 11:05 UTC, V-Levchenkov commented on server/src/test/java/ru/practicum/shareit/item/repository/CommentRepositoryTest.java
> +    ItemRepository itemRepository;
были проблемы с конфликтами, видимо запутался в папках, когда собирал=)
Исправлено

2022-09-30 11:06 UTC, V-Levchenkov commented on server/pom.xml
> +	<modelVersion>4.0.0</modelVersion>
Done

2022-09-30 11:07 UTC, V-Levchenkov commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
done

2022-09-30 11:12 UTC, V-Levchenkov commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.error("Unknown state: UNSUPPORTED_STATUS" + "\n" + e.getMessage());
done

2022-09-30 11:14 UTC, V-Levchenkov commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +											  @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
done

2022-10-01 08:03 UTC, kukolev requested changes

2022-10-01 08:03 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +	// Все
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-01 08:03 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +	private long itemId;
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-01 08:03 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Получен запрос к эндпоинту: '{} {}', Вещь: Наименование: {} и Описание: {}", "POST", "/items",
Этот и подобные ему логи можно упростить, если сразу писать метод и URL запроса, а не делать их параметрами:
```
log.info("Получен запрос к эндпоинту: 'POST /items', Вещь: Наименование: {} и Описание: {}",
itemDto.getName(), itemDto.getDescription());,
```
Так выглядит лучше. Вообще в параметры при логировании нужно выносить только переменные, значение которых может меняться.

2022-10-01 08:03 UTC, kukolev commented on suppressions.xml
> +		"-//Checkstyle//DTD SuppressionFilter Configuration 1.2//EN"
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-01 09:22 UTC, V-Levchenkov commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Получен запрос к эндпоинту: '{} {}', Вещь: Наименование: {} и Описание: {}", "POST", "/items",
Done

2022-10-01 09:23 UTC, V-Levchenkov commented on suppressions.xml
> +		"-//Checkstyle//DTD SuppressionFilter Configuration 1.2//EN"
done

2022-10-01 09:26 UTC, V-Levchenkov commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +	private long itemId;
Данный DTO был в наборе стартовых классов-примеров от куратора, исправил

2022-10-01 09:27 UTC, V-Levchenkov commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +	private long itemId;
done

2022-10-01 09:28 UTC, V-Levchenkov commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +	// Все
done

2022-10-02 08:05 UTC, kukolev requested changes

2022-10-02 08:05 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.error("Unknown state: UNSUPPORTED_STATUS" + "\n" + "{}", e.getMessage());
Здесь конкатенация строк не нужна, лог можно написать в одну строку, так будет проще:
`log.error("Unknown state: UNSUPPORTED_STATUS\n{}", e.getMessage());`

2022-10-02 08:05 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Получен запрос к эндпоинту: '{} {}', Вещь с Id: {}, Комментарий: {}",
Здесь не исправлено замечание с прошлого ревью: https://github.com/V-Levchenkov/java-shareit/pull/7#discussion_r985067336

Нужно это исправить.

2022-10-02 08:05 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/requests/ItemRequestController.java
> +        log.info("Получен запрос к эндпоинту: '{} {}', Запрос на вещь: Описание: {}",
Здесь не исправлено замечание с прошлого ревью: https://github.com/V-Levchenkov/java-shareit/pull/7#discussion_r985067336

Нужно это исправить.

2022-10-02 08:05 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +        log.info("Получен запрос к эндпоинту: '{} {}', Пользователь: Имя: {} и Email: {}", "POST", "/users",
Здесь не исправлено замечание с прошлого ревью: https://github.com/V-Levchenkov/java-shareit/pull/7#discussion_r985067336

Нужно это исправить.

2022-10-02 08:05 UTC, kukolev commented on server/src/main/java/ru/practicum/shareit/ShareItServer.java
> +		SpringApplication.run(ShareItServer.class, args);
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-02 08:05 UTC, kukolev commented on server/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<BookingDto> findAll(@RequestHeader("X-Sharer-User-Id") long userId, @RequestParam(defaultValue = "ALL") String state, @RequestParam(defaultValue = "0") int from, @RequestParam(default
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-02 08:05 UTC, kukolev commented on server/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<BookingDto> findAllByOwner(@RequestHeader("X-Sharer-User-Id") long userId, @RequestParam(defaultValue = "ALL") String state, @RequestParam(defaultValue = "0") int from, @RequestParam(
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-02 08:17 UTC, V-Levchenkov commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.error("Unknown state: UNSUPPORTED_STATUS" + "\n" + "{}", e.getMessage());
исправлено

2022-10-02 08:21 UTC, V-Levchenkov commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Получен запрос к эндпоинту: '{} {}', Вещь с Id: {}, Комментарий: {}",
Исправлено

2022-10-02 08:21 UTC, V-Levchenkov commented on gateway/src/main/java/ru/practicum/shareit/requests/ItemRequestController.java
> +        log.info("Получен запрос к эндпоинту: '{} {}', Запрос на вещь: Описание: {}",
исправлено

2022-10-02 08:22 UTC, V-Levchenkov commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +        log.info("Получен запрос к эндпоинту: '{} {}', Пользователь: Имя: {} и Email: {}", "POST", "/users",
Исправлено

2022-10-02 08:23 UTC, V-Levchenkov commented on server/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<BookingDto> findAll(@RequestHeader("X-Sharer-User-Id") long userId, @RequestParam(defaultValue = "ALL") String state, @RequestParam(defaultValue = "0") int from, @RequestParam(default
Исправлено

2022-10-02 08:26 UTC, V-Levchenkov commented on server/src/main/java/ru/practicum/shareit/ShareItServer.java
> +		SpringApplication.run(ShareItServer.class, args);
исправлено

2022-10-02 08:36 UTC, V-Levchenkov commented on server/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<BookingDto> findAllByOwner(@RequestHeader("X-Sharer-User-Id") long userId, @RequestParam(defaultValue = "ALL") String state, @RequestParam(defaultValue = "0") int from, @RequestParam(
исправлено

2022-10-02 13:44 UTC, kukolev approved these changes

2022-10-02 13:56 UTC, merged